### ISSUE TITLE
tedb updates brokes lib

### ISSUE THREAD

**Issue by chocobn69** [airgproducts/eurovat#1]
It looks like tedb just changed their website.

eurovat python lib does not work anymore.

The good news is they provide a webservice now : https://ec.europa.eu/taxation_customs/tedb/ws/VatRetrievalService.wsdl

**Comment by hiaselhans** [comment]
thanks @chocobn69 !

looks like they still have a json rest service too:
https://ec.europa.eu/taxation_customs/tedb/rest-api/vatSearch
https://ec.europa.eu/taxation_customs/tedb/#/vat-search

**Comment by chocobn69** [comment]
Ok, I just forked, I'm going to test this today.

**Comment by hiaselhans** [comment]
wow, great! thank you!

**Comment by chocobn69** [comment]
Here is the merge request related to this issue https://github.com/airgproducts/eurovat/pull/2

**Comment by chocobn69** [comment]
Can you help me with the tests ? I don't know if failing tests are really failing or not ...

**Comment by chocobn69** [comment]
BTW I updated module to match `0.10.1`

**Comment by hiaselhans** [comment]
thanks!
deployed to pypi...
